from pydantic import BaseModel, Field
from typing import List, Optional, Dict
from datetime import datetime

#Base class for Patient
class PatientBase(BaseModel):
    clinic_id: str  # Unique identifier for the patient, provided by the clinic

#Created patient automatically has id
class PatientCreate(PatientBase):
    pass

class PatientResponse(PatientBase):
    id: int                # The unique ID generated by the DB
    created_at: datetime    # The timestamp of when they were added


